### ISSUE TITLE
RemoteReserver does not go to correct room when there is more than one

### ISSUE THREAD

**Issue by UhmBrock** [jakesboy2/screeps-typescript-starter#26]
When there is more than one remote room to choose from, both reservers will go to the same room, instead of reserving two separate rooms.

**Comment by UhmBrock** [comment]
JakesboyFBI: 11:07 PM
Solution: edit the function that finds the target room for a remote reserver to ALSO check that no other remote reserver is targeting that room

Location: RemoteReserverBodyOptsHelper

**Comment by jakesboy2** [comment]
Fixed in TOWER_DRAINER branch, marking as closed for now we can reopen if it ends up not fixing it
