### ISSUE TITLE
RoomVisual code files are all in a folder under manager

### ISSUE THREAD

**Issue by jakesboy2** [jakesboy2/screeps-typescript-starter#30]
Two options here

1. Move room visual api to the api folder and room visual helper to the helper folder, and get rid of the room visual folder

2. Move everything into a top level folder instead of being split by manager api and helper (ie, Room would contain roomApi, roomManager, and roomHelper, for every separation of code we have)

**Comment by UhmBrock** [comment]
This has been completed during a previous refactor.
