### ISSUE TITLE
Remote flag is considered unprocessed twice until finally processing the third time

### ISSUE THREAD

**Issue by jakesboy2** [jakesboy2/screeps-typescript-starter#31]
<img width="323" alt="Screen Shot 2019-11-25 at 8 40 56 AM" src="https://user-images.githubusercontent.com/18545852/69549731-71932580-0f5f-11ea-97b1-9e8a4d5872ea.png">

This is the result of placing a yellow yellow flag. Happens consistently

**Comment by UhmBrock** [comment]
Removing and reworking flag system, so do not need to fix this.
